//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPServiceServer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUtilService")]
    public interface IUtilService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilService/GetClients", ReplyAction="http://tempuri.org/IUtilService/GetClientsResponse")]
        string GetClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilService/GetSellers", ReplyAction="http://tempuri.org/IUtilService/GetSellersResponse")]
        string GetSellers();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtilServiceChannel : HTTPServiceServer.ServiceReference1.IUtilService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilServiceClient : System.ServiceModel.ClientBase<HTTPServiceServer.ServiceReference1.IUtilService>, HTTPServiceServer.ServiceReference1.IUtilService {
        
        public UtilServiceClient() {
        }
        
        public UtilServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetClients() {
            return base.Channel.GetClients();
        }
        
        public string GetSellers() {
            return base.Channel.GetSellers();
        }
    }
}
